//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="OnlineBatchReceiverSoap", Namespace="http://AltInn.no/webservices/")]
public partial class OnlineBatchReceiver : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback ReceiveOnlineBatchExternalAttachmentOperationCompleted;
    
    /// <remarks/>
    public OnlineBatchReceiver() {
        this.Url = "http://localhost/OnlineBatchReceiver/OnlineBatchReceiver.asmx";
    }
    
    /// <remarks/>
    public event ReceiveOnlineBatchExternalAttachmentCompletedEventHandler ReceiveOnlineBatchExternalAttachmentCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://AltInn.no/webservices/ReceiveOnlineBatchExternalAttachment", RequestNamespace="http://AltInn.no/webservices/", ResponseNamespace="http://AltInn.no/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string ReceiveOnlineBatchExternalAttachment(string username, string passwd, string receiversReference, long sequenceNumber, string batch, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] attachments) {
        object[] results = this.Invoke("ReceiveOnlineBatchExternalAttachment", new object[] {
                    username,
                    passwd,
                    receiversReference,
                    sequenceNumber,
                    batch,
                    attachments});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginReceiveOnlineBatchExternalAttachment(string username, string passwd, string receiversReference, long sequenceNumber, string batch, byte[] attachments, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ReceiveOnlineBatchExternalAttachment", new object[] {
                    username,
                    passwd,
                    receiversReference,
                    sequenceNumber,
                    batch,
                    attachments}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndReceiveOnlineBatchExternalAttachment(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void ReceiveOnlineBatchExternalAttachmentAsync(string username, string passwd, string receiversReference, long sequenceNumber, string batch, byte[] attachments) {
        this.ReceiveOnlineBatchExternalAttachmentAsync(username, passwd, receiversReference, sequenceNumber, batch, attachments, null);
    }
    
    /// <remarks/>
    public void ReceiveOnlineBatchExternalAttachmentAsync(string username, string passwd, string receiversReference, long sequenceNumber, string batch, byte[] attachments, object userState) {
        if ((this.ReceiveOnlineBatchExternalAttachmentOperationCompleted == null)) {
            this.ReceiveOnlineBatchExternalAttachmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReceiveOnlineBatchExternalAttachmentOperationCompleted);
        }
        this.InvokeAsync("ReceiveOnlineBatchExternalAttachment", new object[] {
                    username,
                    passwd,
                    receiversReference,
                    sequenceNumber,
                    batch,
                    attachments}, this.ReceiveOnlineBatchExternalAttachmentOperationCompleted, userState);
    }
    
    private void OnReceiveOnlineBatchExternalAttachmentOperationCompleted(object arg) {
        if ((this.ReceiveOnlineBatchExternalAttachmentCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ReceiveOnlineBatchExternalAttachmentCompleted(this, new ReceiveOnlineBatchExternalAttachmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void ReceiveOnlineBatchExternalAttachmentCompletedEventHandler(object sender, ReceiveOnlineBatchExternalAttachmentCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ReceiveOnlineBatchExternalAttachmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ReceiveOnlineBatchExternalAttachmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
