//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BadASBusiness.GiveMeSome {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
    [System.SerializableAttribute()]
    public partial class AltinnFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltinnErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltinnExtendedErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltinnLocalizedErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnErrorMessage {
            get {
                return this.AltinnErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.AltinnErrorMessageField, value) != true)) {
                    this.AltinnErrorMessageField = value;
                    this.RaisePropertyChanged("AltinnErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnExtendedErrorMessage {
            get {
                return this.AltinnExtendedErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.AltinnExtendedErrorMessageField, value) != true)) {
                    this.AltinnExtendedErrorMessageField = value;
                    this.RaisePropertyChanged("AltinnExtendedErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnLocalizedErrorMessage {
            get {
                return this.AltinnLocalizedErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.AltinnLocalizedErrorMessageField, value) != true)) {
                    this.AltinnLocalizedErrorMessageField = value;
                    this.RaisePropertyChanged("AltinnLocalizedErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorGuid {
            get {
                return this.ErrorGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorGuidField, value) != true)) {
                    this.ErrorGuidField = value;
                    this.RaisePropertyChanged("ErrorGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorID {
            get {
                return this.ErrorIDField;
            }
            set {
                if ((this.ErrorIDField.Equals(value) != true)) {
                    this.ErrorIDField = value;
                    this.RaisePropertyChanged("ErrorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserGuid {
            get {
                return this.UserGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.UserGuidField, value) != true)) {
                    this.UserGuidField = value;
                    this.RaisePropertyChanged("UserGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Signature", Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10")]
    [System.SerializableAttribute()]
    public partial class Signature : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndUserSystemReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndUserSystemUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndUserSystemLoginDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndUserSystemSignatureDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndUserSystemVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndUserSystemSignatureLogIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EndUserSystemReference {
            get {
                return this.EndUserSystemReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.EndUserSystemReferenceField, value) != true)) {
                    this.EndUserSystemReferenceField = value;
                    this.RaisePropertyChanged("EndUserSystemReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EndUserSystemUserId {
            get {
                return this.EndUserSystemUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EndUserSystemUserIdField, value) != true)) {
                    this.EndUserSystemUserIdField = value;
                    this.RaisePropertyChanged("EndUserSystemUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime EndUserSystemLoginDateTime {
            get {
                return this.EndUserSystemLoginDateTimeField;
            }
            set {
                if ((this.EndUserSystemLoginDateTimeField.Equals(value) != true)) {
                    this.EndUserSystemLoginDateTimeField = value;
                    this.RaisePropertyChanged("EndUserSystemLoginDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime EndUserSystemSignatureDateTime {
            get {
                return this.EndUserSystemSignatureDateTimeField;
            }
            set {
                if ((this.EndUserSystemSignatureDateTimeField.Equals(value) != true)) {
                    this.EndUserSystemSignatureDateTimeField = value;
                    this.RaisePropertyChanged("EndUserSystemSignatureDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string EndUserSystemVersion {
            get {
                return this.EndUserSystemVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.EndUserSystemVersionField, value) != true)) {
                    this.EndUserSystemVersionField = value;
                    this.RaisePropertyChanged("EndUserSystemVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string EndUserSystemSignatureLogId {
            get {
                return this.EndUserSystemSignatureLogIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EndUserSystemSignatureLogIdField, value) != true)) {
                    this.EndUserSystemSignatureLogIdField = value;
                    this.RaisePropertyChanged("EndUserSystemSignatureLogId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiptExternalBE", Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10")]
    [System.SerializableAttribute()]
    public partial class ReceiptExternalBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReceiptIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiptTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiptHistoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastChangedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BadASBusiness.GiveMeSome.ReceiptTypeExternal ReceiptTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BadASBusiness.GiveMeSome.ReceiptStatusExternal ReceiptStatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParentReceiptIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BadASBusiness.GiveMeSome.ArrayOfReferenceExternalBE ReferencesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BadASBusiness.GiveMeSome.ReceiptExternalBE[] SubReceiptsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReceiptId {
            get {
                return this.ReceiptIdField;
            }
            set {
                if ((this.ReceiptIdField.Equals(value) != true)) {
                    this.ReceiptIdField = value;
                    this.RaisePropertyChanged("ReceiptId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReceiptText {
            get {
                return this.ReceiptTextField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiptTextField, value) != true)) {
                    this.ReceiptTextField = value;
                    this.RaisePropertyChanged("ReceiptText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ReceiptHistory {
            get {
                return this.ReceiptHistoryField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiptHistoryField, value) != true)) {
                    this.ReceiptHistoryField = value;
                    this.RaisePropertyChanged("ReceiptHistory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime LastChanged {
            get {
                return this.LastChangedField;
            }
            set {
                if ((this.LastChangedField.Equals(value) != true)) {
                    this.LastChangedField = value;
                    this.RaisePropertyChanged("LastChanged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public BadASBusiness.GiveMeSome.ReceiptTypeExternal ReceiptTypeName {
            get {
                return this.ReceiptTypeNameField;
            }
            set {
                if ((this.ReceiptTypeNameField.Equals(value) != true)) {
                    this.ReceiptTypeNameField = value;
                    this.RaisePropertyChanged("ReceiptTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public BadASBusiness.GiveMeSome.ReceiptStatusExternal ReceiptStatusCode {
            get {
                return this.ReceiptStatusCodeField;
            }
            set {
                if ((this.ReceiptStatusCodeField.Equals(value) != true)) {
                    this.ReceiptStatusCodeField = value;
                    this.RaisePropertyChanged("ReceiptStatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int ParentReceiptId {
            get {
                return this.ParentReceiptIdField;
            }
            set {
                if ((this.ParentReceiptIdField.Equals(value) != true)) {
                    this.ParentReceiptIdField = value;
                    this.RaisePropertyChanged("ParentReceiptId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public BadASBusiness.GiveMeSome.ArrayOfReferenceExternalBE References {
            get {
                return this.ReferencesField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferencesField, value) != true)) {
                    this.ReferencesField = value;
                    this.RaisePropertyChanged("References");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public BadASBusiness.GiveMeSome.ReceiptExternalBE[] SubReceipts {
            get {
                return this.SubReceiptsField;
            }
            set {
                if ((object.ReferenceEquals(this.SubReceiptsField, value) != true)) {
                    this.SubReceiptsField = value;
                    this.RaisePropertyChanged("SubReceipts");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiptTypeExternal", Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10")]
    public enum ReceiptTypeExternal : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FormTask = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Correspondence = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PINCODE = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Subscription = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Outbound = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PreFill = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDLS = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSF = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterER = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFProperty = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFStreet = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFCountry = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFUser = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LookUp = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFStreetAdd = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFPropertyAdd = 16,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiptStatusExternal", Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10")]
    public enum ReceiptStatusExternal : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnExpectedError = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ValidationFailed = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejected = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfReferenceExternalBE", Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10", ItemName="ReferenceBE")]
    [System.SerializableAttribute()]
    public class ArrayOfReferenceExternalBE : System.Collections.Generic.List<BadASBusiness.GiveMeSome.ReferenceExternalBE> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReferenceExternalBE", Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10")]
    [System.SerializableAttribute()]
    public partial class ReferenceExternalBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceValueField;
        
        private BadASBusiness.GiveMeSome.ReferenceTypeExternal ReferenceTypeNameField;
        
        private int ReporteeIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReferenceValue {
            get {
                return this.ReferenceValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceValueField, value) != true)) {
                    this.ReferenceValueField = value;
                    this.RaisePropertyChanged("ReferenceValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public BadASBusiness.GiveMeSome.ReferenceTypeExternal ReferenceTypeName {
            get {
                return this.ReferenceTypeNameField;
            }
            set {
                if ((this.ReferenceTypeNameField.Equals(value) != true)) {
                    this.ReferenceTypeNameField = value;
                    this.RaisePropertyChanged("ReferenceTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int ReporteeID {
            get {
                return this.ReporteeIDField;
            }
            set {
                if ((this.ReporteeIDField.Equals(value) != true)) {
                    this.ReporteeIDField = value;
                    this.RaisePropertyChanged("ReporteeID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReferenceTypeExternal", Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10")]
    public enum ReferenceTypeExternal : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExternalShipmentReference = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EndUserSystemReference = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ParentReference = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SendersReference = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WorkFlowReference = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BatchReference = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OutboundShipmentReference = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReceiversReference = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Altinn1Reference = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OwnerPartyReference = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartyReference = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ArchiveReference = 12,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FormTaskShipmentBE", Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10")]
    [System.SerializableAttribute()]
    public partial class FormTaskShipmentBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReporteeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalShipmentReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BadASBusiness.GiveMeSome.FormTask FormTasksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BadASBusiness.GiveMeSome.Attachment[] AttachmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BadASBusiness.GiveMeSome.Signature SignaturesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsUserDelegationLockedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserDefinedNumberOfSignaturesRequiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BadASBusiness.GiveMeSome.DelegatedUserBE[] UsersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BadASBusiness.GiveMeSome.EncryptedKeyBE EncryptedKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CaseIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Reportee {
            get {
                return this.ReporteeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReporteeField, value) != true)) {
                    this.ReporteeField = value;
                    this.RaisePropertyChanged("Reportee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ExternalShipmentReference {
            get {
                return this.ExternalShipmentReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalShipmentReferenceField, value) != true)) {
                    this.ExternalShipmentReferenceField = value;
                    this.RaisePropertyChanged("ExternalShipmentReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public BadASBusiness.GiveMeSome.FormTask FormTasks {
            get {
                return this.FormTasksField;
            }
            set {
                if ((object.ReferenceEquals(this.FormTasksField, value) != true)) {
                    this.FormTasksField = value;
                    this.RaisePropertyChanged("FormTasks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public BadASBusiness.GiveMeSome.Attachment[] Attachments {
            get {
                return this.AttachmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachmentsField, value) != true)) {
                    this.AttachmentsField = value;
                    this.RaisePropertyChanged("Attachments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public BadASBusiness.GiveMeSome.Signature Signatures {
            get {
                return this.SignaturesField;
            }
            set {
                if ((object.ReferenceEquals(this.SignaturesField, value) != true)) {
                    this.SignaturesField = value;
                    this.RaisePropertyChanged("Signatures");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool IsUserDelegationLocked {
            get {
                return this.IsUserDelegationLockedField;
            }
            set {
                if ((this.IsUserDelegationLockedField.Equals(value) != true)) {
                    this.IsUserDelegationLockedField = value;
                    this.RaisePropertyChanged("IsUserDelegationLocked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int UserDefinedNumberOfSignaturesRequired {
            get {
                return this.UserDefinedNumberOfSignaturesRequiredField;
            }
            set {
                if ((this.UserDefinedNumberOfSignaturesRequiredField.Equals(value) != true)) {
                    this.UserDefinedNumberOfSignaturesRequiredField = value;
                    this.RaisePropertyChanged("UserDefinedNumberOfSignaturesRequired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public BadASBusiness.GiveMeSome.DelegatedUserBE[] Users {
            get {
                return this.UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersField, value) != true)) {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public BadASBusiness.GiveMeSome.EncryptedKeyBE EncryptedKey {
            get {
                return this.EncryptedKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EncryptedKeyField, value) != true)) {
                    this.EncryptedKeyField = value;
                    this.RaisePropertyChanged("EncryptedKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.Nullable<int> CaseID {
            get {
                return this.CaseIDField;
            }
            set {
                if ((this.CaseIDField.Equals(value) != true)) {
                    this.CaseIDField = value;
                    this.RaisePropertyChanged("CaseID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FormTask", Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10")]
    [System.SerializableAttribute()]
    public partial class FormTask : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ServiceEditionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BadASBusiness.GiveMeSome.Form[] FormsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ServiceCode {
            get {
                return this.ServiceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceCodeField, value) != true)) {
                    this.ServiceCodeField = value;
                    this.RaisePropertyChanged("ServiceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ServiceEdition {
            get {
                return this.ServiceEditionField;
            }
            set {
                if ((this.ServiceEditionField.Equals(value) != true)) {
                    this.ServiceEditionField = value;
                    this.RaisePropertyChanged("ServiceEdition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public BadASBusiness.GiveMeSome.Form[] Forms {
            get {
                return this.FormsField;
            }
            set {
                if ((object.ReferenceEquals(this.FormsField, value) != true)) {
                    this.FormsField = value;
                    this.RaisePropertyChanged("Forms");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EncryptedKeyBE", Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10")]
    [System.SerializableAttribute()]
    public partial class EncryptedKeyBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BadASBusiness.GiveMeSome.ReporteeSymmetricKeyBE ReporteeSymmetricKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BadASBusiness.GiveMeSome.ServiceOwnerSymmetricKeyBE[] ServiceOwnerSymmetricKeysField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public BadASBusiness.GiveMeSome.ReporteeSymmetricKeyBE ReporteeSymmetricKey {
            get {
                return this.ReporteeSymmetricKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ReporteeSymmetricKeyField, value) != true)) {
                    this.ReporteeSymmetricKeyField = value;
                    this.RaisePropertyChanged("ReporteeSymmetricKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public BadASBusiness.GiveMeSome.ServiceOwnerSymmetricKeyBE[] ServiceOwnerSymmetricKeys {
            get {
                return this.ServiceOwnerSymmetricKeysField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceOwnerSymmetricKeysField, value) != true)) {
                    this.ServiceOwnerSymmetricKeysField = value;
                    this.RaisePropertyChanged("ServiceOwnerSymmetricKeys");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Attachment", Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10")]
    [System.SerializableAttribute()]
    public partial class Attachment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndUserSystemReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EncryptedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] AttachementDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttachmentTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChecksumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string EndUserSystemReference {
            get {
                return this.EndUserSystemReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.EndUserSystemReferenceField, value) != true)) {
                    this.EndUserSystemReferenceField = value;
                    this.RaisePropertyChanged("EndUserSystemReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ParentReference {
            get {
                return this.ParentReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentReferenceField, value) != true)) {
                    this.ParentReferenceField = value;
                    this.RaisePropertyChanged("ParentReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool Encrypted {
            get {
                return this.EncryptedField;
            }
            set {
                if ((this.EncryptedField.Equals(value) != true)) {
                    this.EncryptedField = value;
                    this.RaisePropertyChanged("Encrypted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public byte[] AttachementData {
            get {
                return this.AttachementDataField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachementDataField, value) != true)) {
                    this.AttachementDataField = value;
                    this.RaisePropertyChanged("AttachementData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string AttachmentTypeName {
            get {
                return this.AttachmentTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachmentTypeNameField, value) != true)) {
                    this.AttachmentTypeNameField = value;
                    this.RaisePropertyChanged("AttachmentTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Checksum {
            get {
                return this.ChecksumField;
            }
            set {
                if ((object.ReferenceEquals(this.ChecksumField, value) != true)) {
                    this.ChecksumField = value;
                    this.RaisePropertyChanged("Checksum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DelegatedUserBE", Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10")]
    [System.SerializableAttribute()]
    public partial class DelegatedUserBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SSNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrgNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint NumberOfSignaturesAllowedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        private BadASBusiness.GiveMeSome.SigningOptions SigningOptionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SSN {
            get {
                return this.SSNField;
            }
            set {
                if ((object.ReferenceEquals(this.SSNField, value) != true)) {
                    this.SSNField = value;
                    this.RaisePropertyChanged("SSN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string OrgNumber {
            get {
                return this.OrgNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.OrgNumberField, value) != true)) {
                    this.OrgNumberField = value;
                    this.RaisePropertyChanged("OrgNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public uint NumberOfSignaturesAllowed {
            get {
                return this.NumberOfSignaturesAllowedField;
            }
            set {
                if ((this.NumberOfSignaturesAllowedField.Equals(value) != true)) {
                    this.NumberOfSignaturesAllowedField = value;
                    this.RaisePropertyChanged("NumberOfSignaturesAllowed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public BadASBusiness.GiveMeSome.SigningOptions SigningOptions {
            get {
                return this.SigningOptionsField;
            }
            set {
                if ((this.SigningOptionsField.Equals(value) != true)) {
                    this.SigningOptionsField = value;
                    this.RaisePropertyChanged("SigningOptions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Form", Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10")]
    [System.SerializableAttribute()]
    public partial class Form : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CompletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataFormatIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DataFormatVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndUserSystemReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParentReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Completed {
            get {
                return this.CompletedField;
            }
            set {
                if ((this.CompletedField.Equals(value) != true)) {
                    this.CompletedField = value;
                    this.RaisePropertyChanged("Completed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DataFormatId {
            get {
                return this.DataFormatIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DataFormatIdField, value) != true)) {
                    this.DataFormatIdField = value;
                    this.RaisePropertyChanged("DataFormatId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DataFormatVersion {
            get {
                return this.DataFormatVersionField;
            }
            set {
                if ((this.DataFormatVersionField.Equals(value) != true)) {
                    this.DataFormatVersionField = value;
                    this.RaisePropertyChanged("DataFormatVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EndUserSystemReference {
            get {
                return this.EndUserSystemReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.EndUserSystemReferenceField, value) != true)) {
                    this.EndUserSystemReferenceField = value;
                    this.RaisePropertyChanged("EndUserSystemReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentReference {
            get {
                return this.ParentReferenceField;
            }
            set {
                if ((this.ParentReferenceField.Equals(value) != true)) {
                    this.ParentReferenceField = value;
                    this.RaisePropertyChanged("ParentReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string FormData {
            get {
                return this.FormDataField;
            }
            set {
                if ((object.ReferenceEquals(this.FormDataField, value) != true)) {
                    this.FormDataField = value;
                    this.RaisePropertyChanged("FormData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SigningOptions", Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10")]
    public enum SigningOptions : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserControlled = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AllAttachments = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AllForms = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReporteeSymmetricKeyBE", Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10")]
    [System.SerializableAttribute()]
    public partial class ReporteeSymmetricKeyBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReporteeIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReporteeId {
            get {
                return this.ReporteeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ReporteeIdField, value) != true)) {
                    this.ReporteeIdField = value;
                    this.RaisePropertyChanged("ReporteeId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceOwnerSymmetricKeyBE", Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10")]
    [System.SerializableAttribute()]
    public partial class ServiceOwnerSymmetricKeyBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceOwnerCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CertificateIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ServiceOwnerCode {
            get {
                return this.ServiceOwnerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceOwnerCodeField, value) != true)) {
                    this.ServiceOwnerCodeField = value;
                    this.RaisePropertyChanged("ServiceOwnerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int CertificateId {
            get {
                return this.CertificateIdField;
            }
            set {
                if ((this.CertificateIdField.Equals(value) != true)) {
                    this.CertificateIdField = value;
                    this.RaisePropertyChanged("CertificateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10", ConfigurationName="GiveMeSome.IIntermediaryInboundExternalBasic")]
    public interface IIntermediaryInboundExternalBasic {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.altinn.no/services/2009/10) of message TestRequest does not match the default value (http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/Test", ReplyAction="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BadASBusiness.GiveMeSome.AltinnFault), Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        BadASBusiness.GiveMeSome.TestResponse Test(BadASBusiness.GiveMeSome.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/Test", ReplyAction="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestResponse")]
        System.Threading.Tasks.Task<BadASBusiness.GiveMeSome.TestResponse> TestAsync(BadASBusiness.GiveMeSome.TestRequest request);
        
        // CODEGEN: Generating message contract since element name systemUserName from namespace http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10/I" +
            "IntermediaryInboundExternalBasic/CompleteAndSignShipmentBasic", ReplyAction="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10/I" +
            "IntermediaryInboundExternalBasic/CompleteAndSignShipmentBasicResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BadASBusiness.GiveMeSome.AltinnFault), Action="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10/I" +
            "IntermediaryInboundExternalBasic/CompleteAndSignShipmentBasicAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        BadASBusiness.GiveMeSome.CompleteAndSignShipmentBasicResponse CompleteAndSignShipmentBasic(BadASBusiness.GiveMeSome.CompleteAndSignShipmentBasicRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10/I" +
            "IntermediaryInboundExternalBasic/CompleteAndSignShipmentBasic", ReplyAction="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10/I" +
            "IntermediaryInboundExternalBasic/CompleteAndSignShipmentBasicResponse")]
        System.Threading.Tasks.Task<BadASBusiness.GiveMeSome.CompleteAndSignShipmentBasicResponse> CompleteAndSignShipmentBasicAsync(BadASBusiness.GiveMeSome.CompleteAndSignShipmentBasicRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10/I" +
            "IntermediaryInboundExternalBasic/GetAltinnSubmissionStatusBasic", ReplyAction="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10/I" +
            "IntermediaryInboundExternalBasic/GetAltinnSubmissionStatusBasicResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BadASBusiness.GiveMeSome.AltinnFault), Action="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10/I" +
            "IntermediaryInboundExternalBasic/GetAltinnSubmissionStatusBasicAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        int GetAltinnSubmissionStatusBasic(string systemUserName, string systemPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10/I" +
            "IntermediaryInboundExternalBasic/GetAltinnSubmissionStatusBasic", ReplyAction="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10/I" +
            "IntermediaryInboundExternalBasic/GetAltinnSubmissionStatusBasicResponse")]
        System.Threading.Tasks.Task<int> GetAltinnSubmissionStatusBasicAsync(string systemUserName, string systemPassword);
        
        // CODEGEN: Generating message contract since element name systemUserName from namespace http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10/I" +
            "IntermediaryInboundExternalBasic/SubmitFormTaskBasic", ReplyAction="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10/I" +
            "IntermediaryInboundExternalBasic/SubmitFormTaskBasicResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BadASBusiness.GiveMeSome.AltinnFault), Action="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10/I" +
            "IntermediaryInboundExternalBasic/SubmitFormTaskBasicAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        BadASBusiness.GiveMeSome.SubmitFormTaskBasicResponse SubmitFormTaskBasic(BadASBusiness.GiveMeSome.SubmitFormTaskBasicRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10/I" +
            "IntermediaryInboundExternalBasic/SubmitFormTaskBasic", ReplyAction="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10/I" +
            "IntermediaryInboundExternalBasic/SubmitFormTaskBasicResponse")]
        System.Threading.Tasks.Task<BadASBusiness.GiveMeSome.SubmitFormTaskBasicResponse> SubmitFormTaskBasicAsync(BadASBusiness.GiveMeSome.SubmitFormTaskBasicRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Test", WrapperNamespace="http://www.altinn.no/services/2009/10", IsWrapped=true)]
    public partial class TestRequest {
        
        public TestRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestResponse", WrapperNamespace="http://www.altinn.no/services/2009/10", IsWrapped=true)]
    public partial class TestResponse {
        
        public TestResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CompleteAndSignShipmentBasicRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CompleteAndSignShipmentBasic", Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10", Order=0)]
        public BadASBusiness.GiveMeSome.CompleteAndSignShipmentBasicRequestBody Body;
        
        public CompleteAndSignShipmentBasicRequest() {
        }
        
        public CompleteAndSignShipmentBasicRequest(BadASBusiness.GiveMeSome.CompleteAndSignShipmentBasicRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10")]
    public partial class CompleteAndSignShipmentBasicRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string systemUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string systemPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userSSN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string userPinCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string authMethod;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int reporteeElementId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public BadASBusiness.GiveMeSome.Signature[] signatures;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int languageId;
        
        public CompleteAndSignShipmentBasicRequestBody() {
        }
        
        public CompleteAndSignShipmentBasicRequestBody(string systemUserName, string systemPassword, string userSSN, string userPassword, string userPinCode, string authMethod, int reporteeElementId, BadASBusiness.GiveMeSome.Signature[] signatures, int languageId) {
            this.systemUserName = systemUserName;
            this.systemPassword = systemPassword;
            this.userSSN = userSSN;
            this.userPassword = userPassword;
            this.userPinCode = userPinCode;
            this.authMethod = authMethod;
            this.reporteeElementId = reporteeElementId;
            this.signatures = signatures;
            this.languageId = languageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CompleteAndSignShipmentBasicResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CompleteAndSignShipmentBasicResponse", Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10", Order=0)]
        public BadASBusiness.GiveMeSome.CompleteAndSignShipmentBasicResponseBody Body;
        
        public CompleteAndSignShipmentBasicResponse() {
        }
        
        public CompleteAndSignShipmentBasicResponse(BadASBusiness.GiveMeSome.CompleteAndSignShipmentBasicResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10")]
    public partial class CompleteAndSignShipmentBasicResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BadASBusiness.GiveMeSome.ReceiptExternalBE CompleteAndSignShipmentBasicResult;
        
        public CompleteAndSignShipmentBasicResponseBody() {
        }
        
        public CompleteAndSignShipmentBasicResponseBody(BadASBusiness.GiveMeSome.ReceiptExternalBE CompleteAndSignShipmentBasicResult) {
            this.CompleteAndSignShipmentBasicResult = CompleteAndSignShipmentBasicResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitFormTaskBasicRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitFormTaskBasic", Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10", Order=0)]
        public BadASBusiness.GiveMeSome.SubmitFormTaskBasicRequestBody Body;
        
        public SubmitFormTaskBasicRequest() {
        }
        
        public SubmitFormTaskBasicRequest(BadASBusiness.GiveMeSome.SubmitFormTaskBasicRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10")]
    public partial class SubmitFormTaskBasicRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string systemUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string systemPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userSSN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string userPinCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string authMethod;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public BadASBusiness.GiveMeSome.FormTaskShipmentBE formTaskShipment;
        
        public SubmitFormTaskBasicRequestBody() {
        }
        
        public SubmitFormTaskBasicRequestBody(string systemUserName, string systemPassword, string userSSN, string userPassword, string userPinCode, string authMethod, BadASBusiness.GiveMeSome.FormTaskShipmentBE formTaskShipment) {
            this.systemUserName = systemUserName;
            this.systemPassword = systemPassword;
            this.userSSN = userSSN;
            this.userPassword = userPassword;
            this.userPinCode = userPinCode;
            this.authMethod = authMethod;
            this.formTaskShipment = formTaskShipment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitFormTaskBasicResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitFormTaskBasicResponse", Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10", Order=0)]
        public BadASBusiness.GiveMeSome.SubmitFormTaskBasicResponseBody Body;
        
        public SubmitFormTaskBasicResponse() {
        }
        
        public SubmitFormTaskBasicResponse(BadASBusiness.GiveMeSome.SubmitFormTaskBasicResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2009/10")]
    public partial class SubmitFormTaskBasicResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BadASBusiness.GiveMeSome.ReceiptExternalBE SubmitFormTaskBasicResult;
        
        public SubmitFormTaskBasicResponseBody() {
        }
        
        public SubmitFormTaskBasicResponseBody(BadASBusiness.GiveMeSome.ReceiptExternalBE SubmitFormTaskBasicResult) {
            this.SubmitFormTaskBasicResult = SubmitFormTaskBasicResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIntermediaryInboundExternalBasicChannel : BadASBusiness.GiveMeSome.IIntermediaryInboundExternalBasic, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntermediaryInboundExternalBasicClient : System.ServiceModel.ClientBase<BadASBusiness.GiveMeSome.IIntermediaryInboundExternalBasic>, BadASBusiness.GiveMeSome.IIntermediaryInboundExternalBasic {
        
        public IntermediaryInboundExternalBasicClient() {
        }
        
        public IntermediaryInboundExternalBasicClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IntermediaryInboundExternalBasicClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntermediaryInboundExternalBasicClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntermediaryInboundExternalBasicClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BadASBusiness.GiveMeSome.TestResponse BadASBusiness.GiveMeSome.IIntermediaryInboundExternalBasic.Test(BadASBusiness.GiveMeSome.TestRequest request) {
            return base.Channel.Test(request);
        }
        
        public void Test() {
            BadASBusiness.GiveMeSome.TestRequest inValue = new BadASBusiness.GiveMeSome.TestRequest();
            BadASBusiness.GiveMeSome.TestResponse retVal = ((BadASBusiness.GiveMeSome.IIntermediaryInboundExternalBasic)(this)).Test(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BadASBusiness.GiveMeSome.TestResponse> BadASBusiness.GiveMeSome.IIntermediaryInboundExternalBasic.TestAsync(BadASBusiness.GiveMeSome.TestRequest request) {
            return base.Channel.TestAsync(request);
        }
        
        public System.Threading.Tasks.Task<BadASBusiness.GiveMeSome.TestResponse> TestAsync() {
            BadASBusiness.GiveMeSome.TestRequest inValue = new BadASBusiness.GiveMeSome.TestRequest();
            return ((BadASBusiness.GiveMeSome.IIntermediaryInboundExternalBasic)(this)).TestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BadASBusiness.GiveMeSome.CompleteAndSignShipmentBasicResponse BadASBusiness.GiveMeSome.IIntermediaryInboundExternalBasic.CompleteAndSignShipmentBasic(BadASBusiness.GiveMeSome.CompleteAndSignShipmentBasicRequest request) {
            return base.Channel.CompleteAndSignShipmentBasic(request);
        }
        
        public BadASBusiness.GiveMeSome.ReceiptExternalBE CompleteAndSignShipmentBasic(string systemUserName, string systemPassword, string userSSN, string userPassword, string userPinCode, string authMethod, int reporteeElementId, BadASBusiness.GiveMeSome.Signature[] signatures, int languageId) {
            BadASBusiness.GiveMeSome.CompleteAndSignShipmentBasicRequest inValue = new BadASBusiness.GiveMeSome.CompleteAndSignShipmentBasicRequest();
            inValue.Body = new BadASBusiness.GiveMeSome.CompleteAndSignShipmentBasicRequestBody();
            inValue.Body.systemUserName = systemUserName;
            inValue.Body.systemPassword = systemPassword;
            inValue.Body.userSSN = userSSN;
            inValue.Body.userPassword = userPassword;
            inValue.Body.userPinCode = userPinCode;
            inValue.Body.authMethod = authMethod;
            inValue.Body.reporteeElementId = reporteeElementId;
            inValue.Body.signatures = signatures;
            inValue.Body.languageId = languageId;
            BadASBusiness.GiveMeSome.CompleteAndSignShipmentBasicResponse retVal = ((BadASBusiness.GiveMeSome.IIntermediaryInboundExternalBasic)(this)).CompleteAndSignShipmentBasic(inValue);
            return retVal.Body.CompleteAndSignShipmentBasicResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BadASBusiness.GiveMeSome.CompleteAndSignShipmentBasicResponse> BadASBusiness.GiveMeSome.IIntermediaryInboundExternalBasic.CompleteAndSignShipmentBasicAsync(BadASBusiness.GiveMeSome.CompleteAndSignShipmentBasicRequest request) {
            return base.Channel.CompleteAndSignShipmentBasicAsync(request);
        }
        
        public System.Threading.Tasks.Task<BadASBusiness.GiveMeSome.CompleteAndSignShipmentBasicResponse> CompleteAndSignShipmentBasicAsync(string systemUserName, string systemPassword, string userSSN, string userPassword, string userPinCode, string authMethod, int reporteeElementId, BadASBusiness.GiveMeSome.Signature[] signatures, int languageId) {
            BadASBusiness.GiveMeSome.CompleteAndSignShipmentBasicRequest inValue = new BadASBusiness.GiveMeSome.CompleteAndSignShipmentBasicRequest();
            inValue.Body = new BadASBusiness.GiveMeSome.CompleteAndSignShipmentBasicRequestBody();
            inValue.Body.systemUserName = systemUserName;
            inValue.Body.systemPassword = systemPassword;
            inValue.Body.userSSN = userSSN;
            inValue.Body.userPassword = userPassword;
            inValue.Body.userPinCode = userPinCode;
            inValue.Body.authMethod = authMethod;
            inValue.Body.reporteeElementId = reporteeElementId;
            inValue.Body.signatures = signatures;
            inValue.Body.languageId = languageId;
            return ((BadASBusiness.GiveMeSome.IIntermediaryInboundExternalBasic)(this)).CompleteAndSignShipmentBasicAsync(inValue);
        }
        
        public int GetAltinnSubmissionStatusBasic(string systemUserName, string systemPassword) {
            return base.Channel.GetAltinnSubmissionStatusBasic(systemUserName, systemPassword);
        }
        
        public System.Threading.Tasks.Task<int> GetAltinnSubmissionStatusBasicAsync(string systemUserName, string systemPassword) {
            return base.Channel.GetAltinnSubmissionStatusBasicAsync(systemUserName, systemPassword);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BadASBusiness.GiveMeSome.SubmitFormTaskBasicResponse BadASBusiness.GiveMeSome.IIntermediaryInboundExternalBasic.SubmitFormTaskBasic(BadASBusiness.GiveMeSome.SubmitFormTaskBasicRequest request) {
            return base.Channel.SubmitFormTaskBasic(request);
        }
        
        public BadASBusiness.GiveMeSome.ReceiptExternalBE SubmitFormTaskBasic(string systemUserName, string systemPassword, string userSSN, string userPassword, string userPinCode, string authMethod, BadASBusiness.GiveMeSome.FormTaskShipmentBE formTaskShipment) {
            BadASBusiness.GiveMeSome.SubmitFormTaskBasicRequest inValue = new BadASBusiness.GiveMeSome.SubmitFormTaskBasicRequest();
            inValue.Body = new BadASBusiness.GiveMeSome.SubmitFormTaskBasicRequestBody();
            inValue.Body.systemUserName = systemUserName;
            inValue.Body.systemPassword = systemPassword;
            inValue.Body.userSSN = userSSN;
            inValue.Body.userPassword = userPassword;
            inValue.Body.userPinCode = userPinCode;
            inValue.Body.authMethod = authMethod;
            inValue.Body.formTaskShipment = formTaskShipment;
            BadASBusiness.GiveMeSome.SubmitFormTaskBasicResponse retVal = ((BadASBusiness.GiveMeSome.IIntermediaryInboundExternalBasic)(this)).SubmitFormTaskBasic(inValue);
            return retVal.Body.SubmitFormTaskBasicResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BadASBusiness.GiveMeSome.SubmitFormTaskBasicResponse> BadASBusiness.GiveMeSome.IIntermediaryInboundExternalBasic.SubmitFormTaskBasicAsync(BadASBusiness.GiveMeSome.SubmitFormTaskBasicRequest request) {
            return base.Channel.SubmitFormTaskBasicAsync(request);
        }
        
        public System.Threading.Tasks.Task<BadASBusiness.GiveMeSome.SubmitFormTaskBasicResponse> SubmitFormTaskBasicAsync(string systemUserName, string systemPassword, string userSSN, string userPassword, string userPinCode, string authMethod, BadASBusiness.GiveMeSome.FormTaskShipmentBE formTaskShipment) {
            BadASBusiness.GiveMeSome.SubmitFormTaskBasicRequest inValue = new BadASBusiness.GiveMeSome.SubmitFormTaskBasicRequest();
            inValue.Body = new BadASBusiness.GiveMeSome.SubmitFormTaskBasicRequestBody();
            inValue.Body.systemUserName = systemUserName;
            inValue.Body.systemPassword = systemPassword;
            inValue.Body.userSSN = userSSN;
            inValue.Body.userPassword = userPassword;
            inValue.Body.userPinCode = userPinCode;
            inValue.Body.authMethod = authMethod;
            inValue.Body.formTaskShipment = formTaskShipment;
            return ((BadASBusiness.GiveMeSome.IIntermediaryInboundExternalBasic)(this)).SubmitFormTaskBasicAsync(inValue);
        }
    }
}
